import { KnowledgeItem } from './types';

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
}

export const MOCK_DATA: KnowledgeItem[] = [
  {
    id: generateId(),
    title: '费曼学习法的核心原理',
    content: '费曼学习法的核心步骤：\n\n1. 选择一个概念\n2. 用简单语言教给别人（或假装教）\n3. 找到自己卡壳的地方\n4. 回到原始材料，重新学习\n5. 简化语言，用类比来解释\n\n关键洞察：如果你不能用简单的语言解释一件事，说明你还没有真正理解它。这个方法强迫你主动处理知识，而非被动接收。',
    category: '阅读',
    tags: ['学习方法', '费曼', '认知科学'],
    source: 'https://fs.blog/feynman-technique/',
    note: '可以用在任何新知识的学习上，尤其是遇到复杂概念时。核心是"以教代学"。',
    isFavorite: true,
    reviewCount: 3,
    lastReviewedAt: '2026-03-18T10:00:00.000Z',
    createdAt: '2026-03-10T08:30:00.000Z',
    updatedAt: '2026-03-10T08:30:00.000Z',
  },
  {
    id: generateId(),
    title: 'React Server Components 工作机制',
    content: 'React Server Components (RSC) 允许组件在服务器端渲染，且不会将 JavaScript 发送到客户端。\n\n核心要点：\n- Server Components 默认在服务器运行，不能使用 useState、useEffect\n- Client Components 使用 "use client" 指令标记\n- Server Components 可以 import Client Components，反之不行\n- 数据获取直接在组件中使用 async/await\n- 减少客户端 JS bundle 大小，提升首屏性能\n\n最佳实践：将交互逻辑下推到叶子节点的 Client Components，保持页面级组件为 Server Components。',
    category: '技术',
    tags: ['React', 'RSC', '前端架构', 'Next.js'],
    source: 'https://react.dev/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023',
    note: 'Next.js App Router 默认就是 RSC，这是未来 React 的主流模式。',
    isFavorite: true,
    reviewCount: 2,
    lastReviewedAt: '2026-03-15T14:00:00.000Z',
    createdAt: '2026-03-08T10:00:00.000Z',
    updatedAt: '2026-03-08T10:00:00.000Z',
  },
  {
    id: generateId(),
    title: '产品 MVP 的正确打开方式',
    content: 'MVP（最小可行产品）的关键误区和正确做法：\n\n❌ 误区：MVP = 做一个简陋的产品\n✅ 正解：MVP = 用最小代价验证最大风险的假设\n\n步骤：\n1. 明确核心假设（用户是否有这个痛点？）\n2. 找到验证假设的最小功能集\n3. 快速构建，快速上线\n4. 收集数据，验证假设\n5. 迭代或转向\n\nMVP 不是关于"最小"，而是关于"可行"——它必须能完整解决一个核心问题。',
    category: '产品',
    tags: ['MVP', '产品思维', '精益创业'],
    source: '',
    note: '做面试笔试项目时也应该用 MVP 思维：先保证核心功能完整可用，再考虑锦上添花。',
    isFavorite: false,
    reviewCount: 1,
    lastReviewedAt: '2026-03-12T09:00:00.000Z',
    createdAt: '2026-03-05T16:00:00.000Z',
    updatedAt: '2026-03-05T16:00:00.000Z',
  },
  {
    id: generateId(),
    title: '设计系统中的间距规范',
    content: '建立一致的间距系统是 UI 设计的基础：\n\n推荐使用 4px 基准网格：\n- 4px：极小间距（图标与文字）\n- 8px：紧凑间距（列表项内部）\n- 12px：常规间距（表单元素）\n- 16px：标准间距（段落间）\n- 24px：区块间距\n- 32px：大区块间距\n- 48px：页面区域间距\n\n原则：\n1. 相关元素间距小，无关元素间距大（亲密性原则）\n2. 全局保持一致的间距比例\n3. 留白也是设计元素，不要害怕空白',
    category: '设计',
    tags: ['设计系统', 'UI设计', '间距', '排版'],
    source: '',
    note: '每次做 UI 时先确定间距规范，可以让整体视觉更统一。Tailwind 的 space 工具类天然符合 4px 网格。',
    isFavorite: false,
    reviewCount: 0,
    lastReviewedAt: null,
    createdAt: '2026-03-12T11:00:00.000Z',
    updatedAt: '2026-03-12T11:00:00.000Z',
  },
  {
    id: generateId(),
    title: '第一性原理思维',
    content: '第一性原理思维（First Principles Thinking）是 Elon Musk 常提到的思维方式：\n\n核心：把问题拆解到最基本的事实，然后从零开始推理，而不是类比已有方案。\n\n例子：\n- 类比思维：「电池很贵，因为一直都很贵」\n- 第一性原理：「电池的原材料成本是多少？如果我们自己采购和组装呢？」\n\n应用场景：\n1. 遇到「大家都这么做」的问题时\n2. 面对看似无解的成本/技术难题时\n3. 需要创新突破时\n\n注意：不是所有场景都需要第一性原理，日常决策用类比更高效。只在关键决策点才值得深度拆解。',
    category: '商业',
    tags: ['思维模型', '第一性原理', '决策'],
    source: '',
    note: '面试中如果被问到"为什么选择这个方案"，用第一性原理来回答会很有说服力。',
    isFavorite: true,
    reviewCount: 4,
    lastReviewedAt: '2026-03-20T08:00:00.000Z',
    createdAt: '2026-03-01T09:00:00.000Z',
    updatedAt: '2026-03-01T09:00:00.000Z',
  },
  {
    id: generateId(),
    title: '番茄工作法的进阶用法',
    content: '基础番茄工作法：25分钟专注 + 5分钟休息\n\n进阶技巧：\n1. **任务预估**：每个任务预估需要几个番茄钟，追踪实际消耗\n2. **内部中断记录**：专注时想到别的事，就记在纸上，继续当前任务\n3. **每日回顾**：统计完成的番茄钟数，分析效率模式\n4. **适应性调整**：深度编程可以用 50+10，写作可以用 25+5\n5. **批处理**：把小任务攒到一个番茄钟里批量处理\n\n关键原则：番茄钟不可分割，被打断就要重新开始。这个规则强迫你保护专注时间。',
    category: '生活',
    tags: ['时间管理', '番茄工作法', '效率'],
    source: '',
    note: '关键不是25分钟这个数字，而是"不可分割的专注时间块"这个概念。',
    isFavorite: false,
    reviewCount: 1,
    lastReviewedAt: '2026-03-14T16:00:00.000Z',
    createdAt: '2026-03-03T14:30:00.000Z',
    updatedAt: '2026-03-03T14:30:00.000Z',
  },
  {
    id: generateId(),
    title: 'TypeScript 类型体操常用技巧',
    content: '实用的 TypeScript 高级类型：\n\n```typescript\n// 1. 条件类型\ntype IsString<T> = T extends string ? true : false;\n\n// 2. 映射类型 - 把所有属性变成可选\ntype MyPartial<T> = { [K in keyof T]?: T[K] };\n\n// 3. 模板字面量类型\ntype EventName = `on${Capitalize<string>}`;\n\n// 4. infer 推断\ntype ReturnType<T> = T extends (...args: any[]) => infer R ? R : never;\n\n// 5. 递归类型\ntype DeepReadonly<T> = {\n  readonly [K in keyof T]: T[K] extends object ? DeepReadonly<T[K]> : T[K];\n};\n```\n\n实际开发中最常用的是 Pick、Omit、Partial、Required 和 Record。',
    category: '技术',
    tags: ['TypeScript', '类型系统', '前端'],
    source: 'https://www.typescriptlang.org/docs/handbook/2/types-from-types.html',
    note: '面试高频考点，尤其是 Partial、Pick、Omit 的实现原理。',
    isFavorite: false,
    reviewCount: 2,
    lastReviewedAt: '2026-03-16T10:00:00.000Z',
    createdAt: '2026-03-07T11:00:00.000Z',
    updatedAt: '2026-03-07T11:00:00.000Z',
  },
  {
    id: generateId(),
    title: '用户访谈的 5 个关键原则',
    content: '做用户访谈时，避免得到无效信息的核心原则：\n\n1. **问过去，不问未来**\n   ❌「你会用这个功能吗？」\n   ✅「上次遇到这个问题你是怎么解决的？」\n\n2. **问具体，不问笼统**\n   ❌「你觉得这个好用吗？」\n   ✅「上次用的时候，哪一步花了你最多时间？」\n\n3. **保持沉默，让用户说**\n   问完问题后安静等待，不要急着填补沉默。\n\n4. **追问"为什么"至少三次**\n   表面回答往往不是真实原因，连续追问才能挖到真实需求。\n\n5. **关注行为，不关注观点**\n   用户说的和做的经常不一致，观察行为比听取意见更重要。',
    category: '产品',
    tags: ['用户研究', '用户访谈', '需求分析'],
    source: 'The Mom Test - Rob Fitzpatrick',
    note: '《The Mom Test》这本书是用户访谈的圣经，核心就是：不要问用户喜不喜欢你的产品。',
    isFavorite: true,
    reviewCount: 0,
    lastReviewedAt: null,
    createdAt: '2026-03-15T13:00:00.000Z',
    updatedAt: '2026-03-15T13:00:00.000Z',
  },
  {
    id: generateId(),
    title: 'Git 分支管理最佳实践',
    content: '中小团队推荐的 Git 分支策略：\n\n**主要分支：**\n- main：生产环境代码，永远可部署\n- develop：开发集成分支\n\n**辅助分支：**\n- feature/*：功能开发分支\n- hotfix/*：紧急修复分支\n- release/*：发版准备分支\n\n**核心规则：**\n1. 永远不直接在 main 上提交\n2. Feature 分支从 develop 创建，完成后合回 develop\n3. 合并前必须 Code Review\n4. 提交信息遵循 Conventional Commits\n5. 保持分支短命（< 3天），避免长期分支\n\nCommit 格式：feat: / fix: / docs: / refactor: / test:',
    category: '技术',
    tags: ['Git', '工程实践', '团队协作'],
    source: '',
    note: '小项目用 GitHub Flow（只有 main + feature）就够了，不需要完整的 Git Flow。',
    isFavorite: false,
    reviewCount: 1,
    lastReviewedAt: '2026-03-19T11:00:00.000Z',
    createdAt: '2026-03-09T09:00:00.000Z',
    updatedAt: '2026-03-09T09:00:00.000Z',
  },
  {
    id: generateId(),
    title: '认知偏差：锚定效应',
    content: '锚定效应（Anchoring Effect）：人们在做决策时，会过度依赖最先接触到的信息（"锚"）。\n\n经典实验：\n- 让两组人猜非洲国家在联合国中的占比\n- A组先看到随机数 10，猜测结果平均 25%\n- B组先看到随机数 65，猜测结果平均 45%\n\n应用场景：\n1. **定价策略**：先展示高价款，再展示目标款\n2. **谈判**：先出价的人设定了锚点\n3. **面试谈薪**：第一个数字会影响整个谈判空间\n4. **产品设计**：套餐定价中的"诱饵选项"\n\n防御方法：意识到锚的存在，主动寻找替代参照物。',
    category: '商业',
    tags: ['认知偏差', '行为经济学', '心理学'],
    source: 'Thinking, Fast and Slow - Daniel Kahneman',
    note: '做产品定价、写提案时都可以利用锚定效应。',
    isFavorite: false,
    reviewCount: 0,
    lastReviewedAt: null,
    createdAt: '2026-03-17T15:00:00.000Z',
    updatedAt: '2026-03-17T15:00:00.000Z',
  },
  {
    id: generateId(),
    title: '配色理论快速入门',
    content: '设计配色的核心知识：\n\n**色彩关系：**\n- 互补色：色轮对面的颜色（高对比，有活力）\n- 类似色：色轮相邻的颜色（和谐，统一）\n- 三等分色：色轮等距三色（丰富但平衡）\n\n**60-30-10 法则：**\n- 60% 主色（背景、大面积）\n- 30% 辅色（卡片、区块）\n- 10% 强调色（按钮、关键操作）\n\n**实用技巧：**\n1. 从一张好看的照片中提取配色\n2. 用色彩表达含义：红=危险/错误，绿=成功，蓝=信任\n3. 确保文字和背景对比度 ≥ 4.5:1（WCAG标准）\n4. 同一色系用不同明度/饱和度创造层次',
    category: '设计',
    tags: ['配色', 'UI设计', '视觉设计'],
    source: '',
    note: '不确定配色时，直接用 Tailwind 的内置色板就很安全。',
    isFavorite: true,
    reviewCount: 2,
    lastReviewedAt: '2026-03-20T14:00:00.000Z',
    createdAt: '2026-03-11T10:00:00.000Z',
    updatedAt: '2026-03-11T10:00:00.000Z',
  },
  {
    id: generateId(),
    title: '如何写好一封工作邮件',
    content: '高效工作邮件的结构：\n\n**标题**：[行动]+[主题]+[时间]（如："请审批：Q2预算方案 - 3月25日前"）\n\n**正文结构：**\n1. **一句话背景**：为什么写这封邮件\n2. **核心请求/结论**：你要对方做什么（放在最前面）\n3. **支撑信息**：必要的细节或数据\n4. **下一步行动**：谁在什么时间做什么\n\n**原则：**\n- 一封邮件只讨论一件事\n- 核心信息在前三行\n- 列表优于长段落\n- 重要信息加粗\n- 抄送人越少越好',
    category: '生活',
    tags: ['职场技能', '沟通', '写作'],
    source: '',
    note: '写邮件和写代码一样，清晰的结构比华丽的辞藻重要得多。',
    isFavorite: false,
    reviewCount: 0,
    lastReviewedAt: null,
    createdAt: '2026-03-19T16:00:00.000Z',
    updatedAt: '2026-03-19T16:00:00.000Z',
  },
];
